### ISSUE TITLE
MangaCow Status 400

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#100]
Getting a Status 400 (Unable to update?) on loading Black Haze on MangaCow.

http://mngcow.co/Black-Haze/213/

Using Chrome 61.0.3148.0 (Official Build) canary (64-bit) on Windows 10 64-bit.

Other titles appear to work fine. Perhaps it's an issue with the manga[title]? The request form has it as "Black-Haze" which may be failing the check.

**Comment by DakuTree** [comment]
Problem was dashes weren't allowed in the title in the backend, but were in the userscript.  
Should be fixed now.
