### ISSUE TITLE
Redundant Codeblock?

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#106]
In the bato.to site integration, it seems to generate the viewer twice, once in presetupviewer, and once again in setobjvars. I'm not sure if this is intended behavior.

https://github.com/DakuTree/manga-tracker/blob/master/public/userscripts/manga-tracker.user.js#L1175-L1179

Although not directly related, if you are able to, could you walk me through how you managed to generate the images from other pages? I tried running the individual jQuery objects, but was only able to find the main image for the page and I have no idea how you pulled the images for the other pages. There are a few sites that use this, but I don't quite know how you successfully implemented it here.

**Comment by DakuTree** [comment]
> In the bato.to site integration, it seems to generate the viewer twice, once in presetupviewer, and once again in setobjvars. I'm not sure if this is intended behavior.

Yeah that is an error. Should only really being doing that if the chapter is a oneshot. Should be fixed now.

> Although not directly related, if you are able to, could you walk me through how you managed to generate the images from other pages? I tried running the individual jQuery objects, but was only able to find the main image for the page and I have no idea how you pulled the images for the other pages. There are a few sites that use this, but I don't quite know how you successfully implemented it here.

We just do a AJAX request on the all possible page urls and scape the image from them using regex.  
Seen here: [#L593](https://github.com/DakuTree/manga-tracker/blob/master/public/userscripts/manga-tracker.user.js#L593) and [#L604](https://github.com/DakuTree/manga-tracker/blob/master/public/userscripts/manga-tracker.user.js#L604)

**Comment by Vesnyx** [comment]
Was able to get through those, but didn't quite get this:
this.viewerChapterURLFormat = this.https+'://bato.to/areader?id='+this.chapter_hash+'&p=' + '%pageN%';

I tried navigating to a test URL with a working hash, but I guess my request isn't going through because I'm missing some headers.
https://bato.to/areader?id=0ddbe01d3f965e35&p=1

Is the process of loading the images through this request method unique to bato.to?

**Comment by DakuTree** [comment]
From what I remember `/areader` URLs require the referrer to be set to `http://bato.to/reader` to work properly.

**Comment by Vesnyx** [comment]
Ah, that makes sense. Time to start working on some other sites.

On another note, is there a limit you'd prefer for the number and types (Scanlator vs Aggregator) of supported sites, or does it not matter?

**Comment by DakuTree** [comment]
Doesn't matter, either is good.
