### ISSUE TITLE
CSS Styling not carried over to searches

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#118]
When a search is initiated and the table displays relevant results, the CSS does not properly differentiate the series. (No alternating colors for each row)

http://i.imgur.com/DREoFnu.png

**Comment by Vesnyx** [comment]
Current fix broke dark theme table header. 

http://i.imgur.com/eGtvmSl.png

**Comment by DakuTree** [comment]
@Vesnyx Should be fixed now.

> Also is light theme supposed to have any row color differentiation? All of the rows currently appear to have the same css styling applied.

Both themes have striped rows, but it is a bit harder to differentiate on the light theme.  
I went ahead and tweaked the color a bit (from #F9F9F9 to #F7F7F7) which should help a bit.

**Comment by Vesnyx** [comment]
Yep, everything seems good now.

**Comment by Vesnyx** [comment]
This does not apply to alternate tabs.

**Comment by DakuTree** [comment]
@Vesnyx Should be fixed now.

**Comment by Vesnyx** [comment]
Sorting columns also breaks this.

**Comment by DakuTree** [comment]
@Vesnyx Fixed.
