### ISSUE TITLE
Western Webcomic Support

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#119]
What's your stance on introducing tracking support for more "Western" webcomics? I don't think it'll be any more difficult to implement support and while it may be dubbed a manga tracker, the site does track various other comic type sites like Webtoons.

**Comment by DakuTree** [comment]
No problem with supporting Western webcomics.  
Honestly as long as the site isn't paywalling on a per chapter basis (like Lezhin/Spottoon), anything is fine.
