### ISSUE TITLE
Split userscript sites into separate files

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#121]
Would be nice if we could split the sites off into separate files like what we've done on the backend. Not too sure how well this could be done considering this is a userscript.  

Guessing using `@require` is the way to go here, but there is a few issues: 
* Really don't want to do mass `@require` for each site. Becomes too bloated too fast.
  A single `@require` which in turn would load all the site files would be nice, but not sure if we can get the `@require` cache to work with that.
* Don't know how `@require` updates compared to the overall userscript.  
  Do they update at the same time, or separately? Need to research this.

Alternative solution is to just have something that compiles everything on deployment, which might be better.

**Comment by Vesnyx** [comment]
Preliminary research indicates that TamperMonkey temporarily caches the current require scripts

[This](https://stackoverflow.com/questions/30109626/how-do-i-prevent-require-from-caching-external-js-scripts) is current information I've found regarding it.

**Comment by Vesnyx** [comment]
Looked up some stuff. 

These are a few options:
[HeadJS](http://headjs.com/)

or 
[Node.js compiler](https://stackoverflow.com/questions/15076581/refactoring-a-userscript-to-use-javascript-modules)

HeadJS would let us split the files, which means we don't need to compile it, but it has to make an external call everytime it wants to load a site module. Node would let us compile on deployment.

**Comment by DakuTree** [comment]
Going to try and work on this a bit when I get back home later today, as the userscript has gotten a bit massive now (3K+ lines). IDE keeps having issues with code formatting because of it, and [scrutinizer-ci](https://scrutinizer-ci.com/g/DakuTree/manga-tracker/issues/master/files/public/userscripts/manga-tracker.user.js?orderField=path&order=asc&honorSelectedPaths=0&languages%5B0%5D=javascript) isn't even able to list all the issues as there is too many.

As for the options:
* `@require` still seems like the best option. Really don't like the fact that each site would need it's own statement though.  
  It's possible we could just have a PHP file dynamically generate & cache a file containing all the sites, but not too sure how `@require` caching would work here. We could just do cache busting with a rewrite rule (I.E: sites.1.js, sites.2.js, sites.3.js etc.).
* HeadJS (or [RequireJS](http://requirejs.org/)) both seem neat, however I'm not too sure about the speed costs. Will do some testing for this.
* Node.js compiler (or similar) is nice, but it also puts an additional wall in front of actually updating the userscript.

**Comment by DakuTree** [comment]
This is mostly done as per 0cd030d7cf596b42f14ec179d48b798e570b2488. Went with the require route.

Few issues with this, mainly from the development end of things:
* Since the site files are required from production, it also makes development a bit tricky since 

Possible solution to all of this is having a separate base userscript, one that uses prod & one that uses dev, but that doesn't really help a new user trying to fix/add things. Can only really point them to modifying the existing sites object?

**Comment by DakuTree** [comment]
Problem is that would require committing them and it wouldn't really solve the issue.

Previously if someone wanted to maybe add/edit support for a site, there was a single file to edit and any changes would be made instantly available to them.
Now we have the situation that if a user does this they don't see changes unless they point the require to a local server hosting the files they are testing, or copy/paste the site to the sites variable > do stuff > copy/paste it back. Bit of an issue.

**Comment by Vesnyx** [comment]
Hmm.... I was thinking something more along the lines of putting the site scripts in a separate branch/repo, similar to AMR. All user would have to do is fork an edit user script with their URL. 

What if we had a testing area inside the script that overrides the previous variable? Users could just add to that to manage or edit new sites.

**Comment by DakuTree** [comment]
For the time being I've just added this to the top of the userscript, which basically does what you mentioned, but using the same format as the userscripts for easy copy/pasting: 
```
(function(sites) {
	//sites['example.com'] = {};
})(window.trackerSites = (window.trackerSites || {}));
```

**Comment by Vesnyx** [comment]
We should also add a dummy response that spits out the update values. Otherwise, since there's no model, especially for new sites, the server will be hit with sources that can't be used. Additionally, it would provide the debugger/contributor with more information regarding what data has been parsed.

**Comment by DakuTree** [comment]
That would be handy, shouldn't be too hard to do either.

Will see about implementing it tomorrow. Need sleep after 11~ hours of coding :sleeping:
