### ISSUE TITLE
MAL ID Image Glitch [Minor]

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#122]
This is a really weird bug I just found. 

Reproduction Steps:
1) Choose a manga
2) Set MAL ID to 0
3) Change MAL ID to any non 0 integer (I only tested with > 0)
4) 3 Sets of icons appear.

Issue goes away when page is refreshed, but remains on the page until then.
Might be due to weird application of CSS.

**Comment by DakuTree** [comment]
Should be fixed as of the above two commits.
