### ISSUE TITLE
Auto-track resets reading state

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#126]
If you go to an older chapter of a series that's already been completed, the auto-track will reset the reading state back to that chapter automatically rather than asking for confirmation. Not sure if this is intended behavior.

**Comment by DakuTree** [comment]
This is intended. We can't tell if the chapter is older or not when tracking it sadly.

**Comment by Vesnyx** [comment]
If the whole chapter list is implemented, the current functionality could be changed right?

**Comment by DakuTree** [comment]
Don't see why not.
