### ISSUE TITLE
Auto-Update Broken

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#137]
Most sites currently failing to auto-track/auto-update on completion of page loading.

**Comment by DakuTree** [comment]
Should be all fixed now. Both this and the auto-scrolling issue in #136.

**Comment by Vesnyx** [comment]
Still doesn't seem like its fixed for bato.to.

**Comment by DakuTree** [comment]
Fixed now. Forgot bato.to delayed the auto-tracking until after all pages are loaded (which is now default).
