### ISSUE TITLE
Batoto Webtoons Loading

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#139]
Whenever a batoto webtoon is loaded, the promise seems to complete immediately, rather than after all the pages have been loaded. This also affects the "pages loaded" notification. It never appears since it thinks the images have all been completely loaded, even though the updatePagesLoaded function is being called.

**Comment by DakuTree** [comment]
> Whenever a batoto webtoon is loaded, the promise seems to complete immediately, rather than after all the pages have been loaded.

This is intentional. We want the promise to resolve after we've generated all the images container, not after all the images have loaded. This is instant for bato.to webtoons as we don't need to scrape other pages for images as they're all on the original page.

> This also affects the "pages loaded" notification. It never appears since it thinks the images have all been completely loaded, even though the updatePagesLoaded function is being called.

This was actually an issue with bato.to webtoons setting page_count late, meaning the notification element wasn't being created. This is fixed as per the above commit.

**Comment by DakuTree** [comment]
That is an issue on bato.to's end. Has been getting more and more worse the past few weeks. 
Some more info on reddit: https://www.reddit.com/r/manga/comments/6qbql5/is_batato_getting_slower/

**Comment by Vesnyx** [comment]
Didn't mean the bato.to page loading. That's as slow as usual. It's more that the element doesn't seem to show until at least 1 page has successfully loaded.

**Comment by DakuTree** [comment]
Should be fixed as per the above commit.

**Comment by Vesnyx** [comment]
Partially related, but not super important. The Promises.all function that is used is called regardless of whether or not the Promise is actually resolved or not. This means that the functions below are always called, even though the images haven't all loaded. Promises are pretty finicky when it comes to their status, so it might be better to switch to jQuery's deferred objects for future work. 

Additionally, one of my future implementations relies on the fact that Promises.all works, so if you have any wisdom on how to use it properly, I'd be all ears.

**Comment by DakuTree** [comment]
> You know how to get promises to work properly inside the onload function?

Shouldn't have to change anything to make it to work in an onload function, it should just work like a normal promise. ([Example](https://jsfiddle.net/Lx6h2n6m/))
Would have to see the actual code to see what is going wrong here.
