### ISSUE TITLE
Duplicate Images on Jaimini's Box

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#142]
On loading and reloading, some pages appear to get duplicated for no apparent reason. Might be an issue with all of the FoolSlide based sites. The image URLs are separated by the domain they're on, but they still represent the same page. Not sure what the root cause is. 

What it looks like on the page itself: 
http://i.imgur.com/3nGwWuh.jpg

**Comment by DakuTree** [comment]
Fixed as of b67a842dc56e18904299a9d8f6d5ba2181f0a55f.
