### ISSUE TITLE
Adding New MAL Entry

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#143]
At the moment, the CRSF method uses an edit.json POST request to modify the reading state, but this only works if the manga is already on the list.  If possible, we should use the POST request with add.json instead, the parameters are the same, but MAL won't add new manga to the list if this is not done.

**Comment by DakuTree** [comment]
The problem with add.json is it only works if the series _isn't_ on the list.  

Would have to check if the user has it added via add.json, and if so, send another request via edit.json.  
Could probably log the users mal status on the backend to reduce requests as well.

**Comment by Vesnyx** [comment]
We could use the tagging system as a way of checking if the user has it on their list or not. I don't know if any error is returned via edit.json or add.json if they are not on the list or already added respectively, but tags could be assigned to verify it and determine the type of request sent.

The official API might be another alternative, but only problem would be user credential storage. It could be stored as a temporary cookie, but that begets a security issue.

**Comment by Vesnyx** [comment]
Did some testing, seems like if you run a post request with add.json and the manga already exists, you get this response:
`{"errors":[{"message":"The manga is already in your list."}]}`

The edit.json response if the manga is not in the list is as follows:
`{"errors":[{"message":"failed to edit"}]}`

We could use the error codes thrown to generate a request of the opposite type. Since edit requests are called more often than add requests, I think the add.json call shown occur on the edit's failure.

**Comment by DakuTree** [comment]
Userscript should now fallback to add.json if edit.son fails due to the above error.
