### ISSUE TITLE
OT Scans Broken

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#150]
Seems like the FoolSlide API update broke OT Scans.

**Comment by DakuTree** [comment]
Should be fixed as per the above commit.

**Comment by Vesnyx** [comment]
Other FoolSlide sites seem broken on the update system. They show the chapters like this: v11/c, when the latest chapter is 11.

**Comment by Vesnyx** [comment]
@DakuTree Also seems like decimals are not being properly recognized. FooSlide seems to replace decimals with a '/' operator instead. Other issues stem from when no volume is assigned, the default volume is 0, resulting in some of the URL's not working.

**Comment by DakuTree** [comment]
_Should_ be fixed now.
