### ISSUE TITLE
The reset password page doesn't work

### ISSUE THREAD

**Issue by MitsuhideA** [DakuTree/manga-tracker#159]
On this page that I received by email: https://trackr.moe/user/reset_password/<randomchars>
It gives me this error : 

> The Password Confirm field does not match the password field.

I tried different passwords but nothing works (example: azerty)

**Comment by MitsuhideA** [comment]
I think the error comes from this line: https://github.com/DakuTree/manga-tracker/blob/ff89bac195dfd8ba49039cd940b2920f3dc40809/application/controllers/User/Auth/Forgot_Password.php#L79
"matches[password]" should be changed to "matches[new_password]".

**Comment by DakuTree** [comment]
Thanks for the report. Should be fixed now.

**Comment by MitsuhideA** [comment]
You're welcome. Thanks for the fast fix!
