### ISSUE TITLE
Updating Read Series in TableSort

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#160]
Since the assignment of read vs unread is done server-side rather than client side, the page must be refreshed to show changes in the sort order. 

In this case, marking a manga initially shown as unread as read will keep its original unread sort order until a page refresh occurs.

**Comment by Vesnyx** [comment]
Fix seems to be working only partially. Upon reading/marking the latest chapter, the sort does not move the manga to it's appropriate position. However, this may be the intended use. On the other hand, when reapplying the sorts on the page itself (e.g. alphabetical via clicking on series name), the list is not properly updated. This only seems to apply to table sort methods. 

Reproduction of steps:
1. Mark manga as read.
2. Sort by unread via the checkbox column.
3. Fails to update.

Something else I noticed is that the checkbox column doesn't have a sort method matching it. You can test this by opening the settings menu to see the sort methods, selecting a sort method, then clicking the check box column sort.

**Comment by DakuTree** [comment]
> Fix seems to be working only partially. Upon reading/marking the latest chapter, the sort does not move the manga to it's appropriate position. However, this may be the intended use.

This is intended. Could probably have an option to auto-resort if it's really needed though.

> On the other hand, when reapplying the sorts on the page itself (e.g. alphabetical via clicking on series name), the list is not properly updated. This only seems to apply to table sort methods.
> ...
> Something else I noticed is that the checkbox column doesn't have a sort method matching it.
> You can test this by opening the settings menu to see the sort methods, selecting a sort method, then clicking the check box column sort.

Both of these methods appear to be working fine on my end.  
Just pushed out a small tweak which _might_ help.

**Comment by Vesnyx** [comment]
The sites now get properly sorted after being read. However, using the checkbox sort doesn't match any of the dropdown sort methods, leaving the dropdown sort blank.

**Comment by DakuTree** [comment]
The unread column can't order alphabetically on it's own as it's just a bunch of 1s (read) and 0s (unread). The initial unread sort is alphabetical only because Tablesorter uses that as a base order when sorting what order those 1s and 0s go, and editting anything will simply move it to the top of the list.  
We also can't change this as we need a normal unread sort for the rest of the unread sorts to work properly.

If you want to do an unread+alphabetical sort from the dashboard you can either:
1. Click the option in the nav dropdown.
2. Shift click the unread & series headers.

**Comment by DakuTree** [comment]
This is fixed as per 9bdd2863405d8e5f9ad1537e0536176ac6a07b9d. (Note that this is only on the new version of the dashboard, not the old one).
