### ISSUE TITLE
bato.to pages occasionally not loading, despite successful response code

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#166]
Noticed this issue today with [this](https://bato.to/reader#f61ebb53b2940812).  
The areader page request returns response code 200 which should be success, but the response data is empty. Appears to happen randomly on the above chapter.

**Comment by Vesnyx** [comment]
Isn't this an issue with recently uploaded chapters? There might be a server-side issue with the time from which the chapter is updated to the point at which the page properly works. I've only seen this issue happen on chapters that have been uploaded within a few hours of my viewing.

**Comment by DakuTree** [comment]
Yeah it only appears to occur with new chapters.  
We just need to do a check that the response actually returns something. 

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
