### ISSUE TITLE
Userscript should Update My Status Chapter Number

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#169]
The chapter number is only changed dynamically upon marking the chapter as latest read. The page must be refreshed in order to see the updated chapter status.

**Comment by Vesnyx** [comment]
I think this broke batoto chapters. Seems like the chapter number being passed is including the hash. 

Example is this:
`37d3e44e571d04a3:--:v1/c2`

It fixes on refresh.

**Comment by DakuTree** [comment]
> Seems like the chapter number being passed is including the hash.

Above commit should fix this.
