### ISSUE TITLE
User Friendly Tag-Searching

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#181]
While the current system works, it would probably be easier for the user if they could search with tags like this:

`tag:comedy,4-koma` rather than `tag:comedy AND tag:4-koma`.

**Comment by DakuTree** [comment]
Might be possible to add this with a [custom filter type](https://mottie.github.io/tablesorter/docs/example-widget-filter-custom-search.html#how_to_add_custom_filter_types).
