### ISSUE TITLE
mal:duplicate metatag

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#188]
Might be useful to find all series that have the ID on more than one series.

Tried to do some work on this but doesn't seem to work at all.
```javascript
case 'duplicate':
	if(data.$row.find('> td:eq(1) i.sprite-myanimelist-net').length > 0) {
		let malID      = data.$row.find('> td:eq(1) i.sprite-myanimelist-net').attr('title'),
		    $foundRows = config.$table.find(`tr > td:nth-of-type(2) i.sprite-myanimelist-net[title=${malID}]`);

		status = ($foundRows.length > 1);
	}

	break;
```
The extremely weird thing here is this works fine when calling it via the console, just not here.

Also useful:
```javascript
if(searchID === 'duplicates') { searchID = 'duplicate'; }
```

**Comment by DakuTree** [comment]
@Vesnyx `mal:any` & `mal:notset` should work for this.

**Comment by Vesnyx** [comment]
They do, but it seems quite finicky. If you don't input the whole search term at once, it seems to narrow down the results before searching. It might be due to me having "New Normal: Class 8" on my list. When I type in "mal:" it shows only New Normal as the result, and typing "notset" or "any" afterwords results in no results showing. Copy pasting or typing fast enough so the search doesn't generate results works however.

**Comment by DakuTree** [comment]
Not seeing this on my end, even with the series you listed above.

Unsure what could be causing this since tablesorter re-filters after any change so it shouldn't matter if it's typed all at once or not.

**Comment by Vesnyx** [comment]
Are you pushing enter after entering the search query? If I don't push enter then I can replicate the error.

**Comment by DakuTree** [comment]
Not pushing enter.

This is what I'm seeing:
![](https://i.imgur.com/f2o5TL9.gif)

**Comment by Vesnyx** [comment]
Maybe it's an issue with the framerate, but are you typing "mal:" letting the results load, and then searching? This is what I get:
![1](https://user-images.githubusercontent.com/4986454/30182791-f6c2ba42-93cc-11e7-95b6-bdb2b00489cc.png)
![2](https://user-images.githubusercontent.com/4986454/30182793-f6caa3f6-93cc-11e7-8712-d74070b81203.png)
![3](https://user-images.githubusercontent.com/4986454/30182792-f6c962de-93cc-11e7-9121-aecfd59e8162.png)

**Comment by DakuTree** [comment]
Ah I'm seeing it now.

That is really weird as it only seems to occur with `mal:`.
`m`, `ma`, `mal` all seem to work fine. It also seems to be only restricted to that category, as switching to other categories shows they were filtered correctly.

Will have a poke around and see if I can find anything. Also going to move this to a separate issue: #201
