### ISSUE TITLE
AMR Importing

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#19]
This would be nice, but would require more site support.

One thing we "could" do is add all AMR sites to the whitelist, but stop them from being tracked. This means they are still added to the users list, and can easily be tracked at a later date. We could also bundle all these into a separate list below the tracking list saying that these sites aren't supported <yet>, but will be?
For the auto-update side of things, we could easily resolve this by simply having a enable_tracking column in tracker_sites.

**Comment by DakuTree** [comment]
I was wanting to get this done for 1.5, but further research shows this isn't as easy as I initially hoped, at least doing it the way I planned on doing it.

Two problems:
* We don't (and won't) support all the sites AMR does. Some of the sites are also no longer even running. I mentioned above we could add these as dummy sites, but that is honestly a bunch of work to do well, and I really can't be assed.
* To make it effective, we'd pretty much have to import majority of what the userscript does into PHP. AMR stores the entire URL for both the title page & the chapter, and we can't parse that with what we have.

Instead of importing, I was considering some form of "helper" instead. We could have a page which checks the JSON, then creates mass links to the chapter pages.
To speed things up, we could allow setting temp options via the URL. We could (hypothetically) auto track & disable viewer via a url arg, which would speed up mass-adding a ton.
It's certainly an idea to think about..

**Comment by DakuTree** [comment]
Went and implemented _most_ of the idea I talked about at the end of the previous comment.
At the moment it just takes the AMR export file and converts it into a user readable list with links. Makes things a _bit_ easier.

Another problem I did notice with it though, is that I forgot AMR does a really terrible job of updating URLs when they change. I have various bato.to urls in like 4 different formats, none of which actually work anymore due to it dropping them all for the chapter ID format they have now. They also stored the chapter URL as the title URL for some reason. No idea why.
Shall see about adding some site-specific tracking info for this, also adding in the userscript auto_track thing later.

**Comment by Vesnyx** [comment]
Can't seem to get this feature to work. List of links doesn't seem to show up, at least for my list.

[This](http://i.imgur.com/eKvLGYq.png) is what displays.

Additionally, [it ](http://i.imgur.com/AHgKGm3.png) seems like the table is generated properly, but the links are never added/properly scraped.

**Comment by DakuTree** [comment]
@Vesnyx : Could you upload/link your AMR export file?

**Comment by Vesnyx** [comment]
https://files.catbox.moe/v1rfra.txt

**Comment by DakuTree** [comment]
Issue should be fixed in the latest commit.

**Comment by Vesnyx** [comment]
Import now works for me. I'll see if I can come up with a better way to handle this.

**Comment by DakuTree** [comment]
Decided to close this. The [import](https://trackr.moe/import_amr) tool we have does a good enough job here, and it's unlikely that anybody still uses AMR due to the lack of updates for mirrors (last one being 09/2017).
