### ISSUE TITLE
MangaFox and MangaHere doesn't work

### ISSUE THREAD

**Issue by doutatsu** [DakuTree/manga-tracker#216]
I don't see any popup for the MangaTracker on MangaFox or MangaHere. I got it working on MangaStream and Webtoons, but there is absolutely nothing on MangaFox, although TemperMonkey does tell me its running. Am I missing something or its a bug?

**Comment by Vesnyx** [comment]
Not getting this issue on MangaHere, but it seems like there are some server issues on MangaFox. Might be related to #213 and #214.

**Comment by doutatsu** [comment]
Ok it seems my AdBlocker was the cause for MangaHere, but not on MangaFox. My bad.

**Comment by doutatsu** [comment]
Ok I wasn't aware how tracker worked. I was expecting the bar to show up, even if it something failed. So MangaHere works sometimes, but MangaFox has been constantly not working. I'd suggest you add html bar with 'error loading' for clearer error handling on the UI side

**Comment by Vesnyx** [comment]
Ok, double-checked. Mangafox is fine. If you're using any sort of ad or element blocker. it's probably causing issues with the background loading.

**Comment by DakuTree** [comment]
MangaFox/MangaHere recently enabled bot protection which is making it a bit tricky for the viewer to work properly as it can't always load the data. Also with their recent switch to https they've started using an ad/tracking cdn for loading images which is also on some adblock lists.

> I'd suggest you add html bar with 'error loading' for clearer error handling on the UI side

Will have a look at adding this.

**Comment by doutatsu** [comment]
@Vesnyx Sometime it works, but most times it doesn't. I would have contributed, but it being written in PHP 😅

**Comment by Vesnyx** [comment]
@doutatsu Could you provide links to any pages that don't work? There might be something different about these pages. 

> it being written in PHP

Actually, that's mostly just the backend. The viewer is generated via Javascript, so if you know a bit, feel free to contribute :)

**Comment by Vesnyx** [comment]
@doutatsu Is this issue still occurring or has it been resolved as of the latest release?

**Comment by doutatsu** [comment]
I haven't noticed anything in awhile now, so I am pretty sure its resolved now. Good job 👍
