### ISSUE TITLE
ReadMangaToday Viewer Broken

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#218]
Don't know what's causing this issue but it seems like the images now have a ?u= attached to the end of the URL.

**Comment by Creepo** [comment]
MangaStream seems to be broken too. If I disable tracker it'll work again
![image](https://user-images.githubusercontent.com/32371552/31139278-45e250f2-a871-11e7-93de-85f69d4c25a6.png)

**Comment by DakuTree** [comment]
Both issues should be fixed as per 09f5815a3cb8c6196342ef09e108242fb5d4c6a4 & 40d8efc9d5c4bc47ea33dcd745ea465113adbd04.
