### ISSUE TITLE
Mangastream doesn't load pages

### ISSUE THREAD

**Issue by SeraphineX** [DakuTree/manga-tracker#219]
This is how Mangastream looks like with ublock disabled and manga tracker enabled: https://i.imgur.com/NGJMJY2.jpg

And this is in incognito mode with ublock enabled and manga tracker disabled: https://i.imgur.com/rasUBKX.jpg

**Comment by DakuTree** [comment]
Not seeing this on my end.
There was a recent issue with images not loading on MangaStream but that was fixed (12~ hours ago](40d8efc9d5c4bc47ea33dcd745ea465113adbd04).

**Comment by Vesnyx** [comment]
Also not seeing this issue on my end. Perhaps its an issue with the URL scheme? I remember MangaStream using a bunch of slightly different URL's, so if it still doesn't work, we can double check on the same one.
