### ISSUE TITLE
Search Results Inconsistent

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#221]
Seems like there's an issue with searches.

If you first search for a word that's in the name of a title (ex. "Grand" from Grand Blue), it works fine. However, if you the word "to" and then a space, it generates a list with weird classifications.

For reference, the search I used to reproduce this was "Grand to ". With the trailing space, otherwise this doesn't work. Also it seems like anything after the "to " gets completely ignored.

**Comment by DakuTree** [comment]
This is fixed as per the above commit (7318e6c1266628312049a24352a2bef7a95c6a66).
Apparently tablesorter was using "to" as a designator for the [range filter](https://mottie.github.io/tablesorter/docs/example-widget-filter-custom-search.html#builtin_filters).
