### ISSUE TITLE
Hatigarm Scans Support

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#226]
Site: http://hatigarmscans.eu/hs/

Seems to be using a (fork?) version of foolslide. 

Yay, another site on the list that I'm still procrastinating. 😨

**Comment by DakuTree** [comment]
Support added in 8044f96e9304f4eb8d34151ecd37f47508df98a0.

For future reference, one way to check if it's a fork or not is to simply check if the API exists or not. (via `api/reader/chapters/orderby/desc_created/format/json`)  
Most forks tend to disable the API for some reason.
