### ISSUE TITLE
Mangastream Website Change

### ISSUE THREAD

**Issue by groundhogxp** [DakuTree/manga-tracker#228]
It seems MangaStream changed again, as support seems to have been lost.

**Comment by Vesnyx** [comment]
Yep, the URL scheme changed. This might be related to #219 
Now it's 
https://mangastream.com/r/(short hand name of manga)/(chapter)/(chapter ID)/(page#)

**Comment by Vesnyx** [comment]
@DakuTree Just letting you know, the site icons name and the css needs to be updated as well since the URL changed.

**Comment by DakuTree** [comment]
@Vesnyx Ahh forgot about them, nice catch.

**Comment by DakuTree** [comment]
Icons should be fixed as per e0ea7185dc2184215b5c4eadd765ade0b1617dbf.
