### ISSUE TITLE
MangaCow Disabled

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#231]
Going by their [facebook](https://www.facebook.com/Mangacow/posts/1717202265008955) they've been having some site issues, to to the point where it doesn't appear to load anymore.

Have disabled it for now, will re-enable when they get around to fixing it.

**Comment by Vesnyx** [comment]
Site is back up again. They're probably not going to update anything for a while. :(

**Comment by DakuTree** [comment]
Have re-enabled it.
