### ISSUE TITLE
Batoto has Cloudflare

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#234]
Seems like they got some security now. Lots of title updates may start failing unless they take it off.

**Comment by DakuTree** [comment]
Apparently the cloudflare protection is just on for an ongoing ddos attack. I have disabled the updates for now to avoid getting ip banned (if not already). Will have a look for a fix when I can.

**Comment by DakuTree** [comment]
Above commit added support for CloudFlare sites which fixes this.

**Comment by Vesnyx** [comment]
Don't know if this got fixed, seems like updates are failing again on batoto links.

**Comment by DakuTree** [comment]
They seemed to have re-enabled it, and it appears to be a bit more aggressive than before which is causing some of the updates to fail. Sometimes works, sometimes doesn't.  
I've updated cfscrape which might help things.

CloudFlare also appears to be enabled on the image domain which is sometimes causing an issue for the viewer. Had a quite a few reports of images not loading.  
Not sure how to go about fixing that though...

**Comment by DakuTree** [comment]
Closing this as Batoto will be dead within the week (#253), and is no longer needed.
