### ISSUE TITLE
Update Fails for Some Manga on LHTranslation

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#235]
http://read.lhtranslation.com/read-kuro-no-souzou-shoukanshi-tenseisha-no-hangyaku--chapter-4.html

For some reason, this manga seems to generate incorrect update parameters. 

Here's the link that trackr provides:
http://read.lhtranslation.com/read-kuro-no-souzou-shoukanshi-tenseisha-no-hangyaku-chapter-4.html

As you can see, the second hyphen is missing in the URL. This title is pretty weird because it has two hyphens at weird spots as well:
http://lhtranslation.com/kuro-no-souzou-shoukanshi-tenseisha-no-hangyaku

This is probably a regex issue on the backend since the information submitted is in this format:
```
manga[site]:read.lhtranslation.com
manga[title]:kuro-no-souzou-shoukanshi-tenseisha-no-hangyaku-
manga[chapter]:4
```

**Comment by DakuTree** [comment]
Problem here is that since we're grabbing the chapter list off the blog, there is a few cases like this where the title is different. Not much we can do outside manual fixes until they get their old chapter list sorted.

Have done a manual fix as per the above commit.
