### ISSUE TITLE
MangaRock support

### ISSUE THREAD

**Issue by doutatsu** [DakuTree/manga-tracker#240]
Was wondering if there are plans to add support for [MangaRock](https://mangarock.com/)? I've been using it more and more, it has great potential and more stable than MangaFox at this point.

**Comment by Vesnyx** [comment]
```
/**
	 * MangaRock
	 * @type {SiteObject}
	 */
	'mangarock.com' : extendSite({
        preInit : function(callback) {
			let dfd = $.Deferred();
			let checkSelector = setInterval(function () {
				if ($('._3Oahl').text() !== '') {
					//AJAX has loaded, resolve deferred.
					dfd.resolve();
					clearInterval(checkSelector);
				} else {
					console.log('trackr - Waiting for initial page load...');
				}
			}, 1000);
			dfd.done(() => {
				callback();
			});
        },
		setObjVars : function() {
            let _this = this;
			this.segments    = window.location.pathname.split( '/' );
			//FIXME: Is there a better way to do this? It just feels like an ugly way of setting vars.
			//this.page_count    = $('.list-switcher-2 > li > select[name=category_type]').get(0).length;
			this.title         = this.segments[2];
			this.chapter       = this.segments[4];

			this.title_url   = this.https + '://mangarock.com/manga/' + this.title;
			this.chapter_url = this.title_url + '/chapter/' + this.chapter;

            let tempList = generateChapterList($('._3Oahl.ll5Bk > select:first > option'), 'value');
            this.chapterList = Object.keys(tempList).reduce(function(result, key) {
				result[_this.title_url + '/chapter/' + key] = tempList[key];
				return result;
			}, {});
            this.chapterListCurrent = this.chapter_url;
		}
	}),
```
Here's some UserScript code. That'll just set the list up. Still debating whether or not I should try to make into a proper viewer, or do something more like WebToons/GoS. Which would you guys prefer @DakuTree and @doutatsu . 

and the include code:
`// @include      /^https?:\/\/mangarock\.com\/manga\/.*?\/chapter\/(.*)?$/`

**Comment by doutatsu** [comment]
I think the list and ability to track is enough. MangaRock has a good viewer, which handles both horizontal and vertical viewing.

**Comment by doutatsu** [comment]
So any progress on this? I'd want to start using MangaRock instead of Batoto rather than MangaFox

**Comment by Vesnyx** [comment]
Sorry, school just started for me again so I haven't had any time to work on it recently. If the viewer is fine, then the only thing that needs to be addressed is the PHP tracker backend and the corresponding additional CSS and images.

**Comment by DakuTree** [comment]
Support has been added as per the above commit.


Going to leave this issue open as there is still two issues:
* No custom updater support yet, should be possible via https://api.mangarockhd.com/query/web400/mrs_latest. Will try and get that added when I can.  
* A refresh is currently required when going from the main site to one of the chapter pages as they use ajax to load page content. Would rather avoid loading the userscript on the entire domain if possible, but might be needed.

**Comment by rjbs91** [comment]
I'm getting an "Unable to update" error when trying to add some series from MangaRock. Is this supposed to happen for now?

**Comment by DakuTree** [comment]
What series?

**Comment by rjbs91** [comment]
Ubel Blatt
Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen
Konya wa Tsuki ga Kirei desu ga, Toriaezu Shine
Gintama
Karneval
Prison School
Bungou Stray Dogs

These are the ones I know. There may be way more series with this problem.

**Comment by DakuTree** [comment]
Try now. Forgot a slash in the chapter format which was causing series with volumes to fail.

**Comment by rjbs91** [comment]
Thanks. It's working now.

**Comment by DakuTree** [comment]
Closing this as the two remaining issues have been split into separate issues (#276 & #277).
