### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#245]
This would be useful to have - https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by Vesnyx** [comment]
Definitely, I was pretty lost when first coming into this project. I'll see if I can compile a list of what I had trouble with.

**Comment by DakuTree** [comment]
Added [ISSUE_TEMPLATE.md](https://github.com/DakuTree/manga-tracker/blob/master/.github/ISSUE_TEMPLATE.md) & [PULL_REQUEST_TEMPLATE.md](https://github.com/DakuTree/manga-tracker/blob/master/.github/PULL_REQUEST_TEMPLATE.md) files which covers most of what CONTRIBUTING.md does.

Going to close this for now, will re-open if we ever get to the point where a CONTRIBUTING.md is needed.
