### ISSUE TITLE
psychoplay and lolscans Site Support

### ISSUE THREAD

**Issue by Creepo** [DakuTree/manga-tracker#249]
Any plans on supporting these sites [LOLScans](https://lolscans.com/) and [Psychoplay](https://psychoplay.co/) in the future?

**Comment by Vesnyx** [comment]
#192 LOLScans is on our to-do list, so we will be trying to get support for that in the future. 

Haven't seen Psychoplay, but it looks nearly identical to the old mangazuki layout, so implementing support should be very easy.

**Comment by DakuTree** [comment]
Both sites are supported as of df27693a2e651128d5369fcf01a20d2b25d77500 & 6fb07d661a52c71feaac3c7bce0753ea7a8d47ff.
