### ISSUE TITLE
Bato.to is closing

### ISSUE THREAD

**Issue by evaryont** [DakuTree/manga-tracker#253]
https://bato.to/forums/topic/28840-batoto-will-be-closing-permanently/

#234 might be related to this. Put up CloudFlare for a last hurrah cache until the servers die along with?

**Comment by Vesnyx** [comment]
Quick question. The batoto titles will remain on our lists right? At least for a while after.  I realize no updates will be performed, but I'd prefer not to miss any series before they get put on mangadex.

**Comment by DakuTree** [comment]
Yeah. The site will just be disabled so updates will stop.

**Comment by DakuTree** [comment]
Batoto is officially dead as of today & tracking has been disabled.
