### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by Creepo** [DakuTree/manga-tracker#264]
## Feature/Site Request

**What is the feature?**
Any possibility of implementing a search function that'll allow to find manga on the sites the tracker supports? This'll probably make it much easier to see if the tracker can track it, adding manga etc.
**Other relevant information:**
If (or if not) the manga is available on different sites it's probably a good idea to show latest released chapter

**Comment by DakuTree** [comment]
No plans for this.  
Wanting to avoid any kind of database search as it just opens up another target for possible legal issues.
