### ISSUE TITLE
Move to seperate server

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#267]
With the massive influx of users the past week (x5 our usual amount), I think it may be worth looking to move trackr.moe to its own server. Mainly to fix some various issues as well as for security reasons.  

This should also help resolve various issues:
* #64 - This is basically just an IP-block issue which will be resolved with the new IP.
* #87 - Since I currently run various other domains on the same server as trackr.moe, reverse dns doesn't work properly, which means we have to use an outside service.

Also see: #55, #207.

**Comment by DakuTree** [comment]
Have started initial work on this. Should hopefully be done before the end of the week.

**Comment by DakuTree** [comment]
All done, seems to work well.

**Comment by lmbesiant** [comment]
I was having no issues with KissManga until about an hour ago.  Is there a new domain?

**Comment by DakuTree** [comment]
@lmbesiant Sounds like you got IP blocked like we did. Not much you can do without getting a new IP.
