### ISSUE TITLE
Request: violentmonkey support

### ISSUE THREAD

**Issue by ramenchef** [DakuTree/manga-tracker#268]
I'd like to request violentmonkey support if possible.  For reasons unknown to me, violentmonkey does not properly load this userscript.

**Comment by rain2reign** [comment]
I temporarily use Tampermonkey for your script. It's fantastic, thank you! **BUT** i do prefer open source addons, like Violentmonkey over Tampermonkey with has been under a proprietary license, since all versions newer than v2.9 . Support for Violentmonkey would be great! :D

**Comment by DakuTree** [comment]
Supported as of 738d0fce3f02cef02f9664d17ec8353d44180509.
