### ISSUE TITLE
Allow importing via Batoto /myfollows?

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#270]
Had a request for this on Twitter. Apparently /myfollows has an export feature now.

Unsure if it's worth it considering the export doesn't contain latest chapter read, and the fact Batoto is dead within a week or so.

**Comment by rain2reign** [comment]
> Update (24-Jan) Notice: You can import your follows (JSON) from Batoto. Your JSON will be saved to the server and I will process them later when the site is less busy, to reduce server lag.

Support is added through the use of JSON. :)

**Comment by Vesnyx** [comment]
Issue may no longer be relevant due to manual migration of series and the existence of MangaDex's migration system.
