### ISSUE TITLE
Webtoons are broken by the script

### ISSUE THREAD

**Issue by Nogooduser** [DakuTree/manga-tracker#271]
As the title says, because the script loads every page and separates them with numbers, series that are meant to be read as one long continuous strip get rather annoying to enjoy because of it.

An example would be ReLIFE where pages end up like [this](https://i.imgur.com/2ATRXCM.png) and it gets distracting to the point where I have to disable the script.

I think there should be some kind of toggle for a webtoon reader on the script so that pages all get put together with no spacing.

**Comment by DakuTree** [comment]
Added as of bebe5625a03870a81380cac207151f9245b8892c.

Toggle it by clicking the image file icon on the toolbar.  
I alsos made it so it will auto-toggle when needed on FoolSlide sites which may make things easier.
