### ISSUE TITLE
MangaDex IDs changed, breaking existing tracking

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#281]
So slightly bad news, when MangaDex imported the Batoto metadata DB it seems to have completely changed the IDs of the series to the Batoto equivilent, and since that is what we use for tracking series it also means tracking is broken for those series.  
I don't know who thought this was a good idea, but what's done is done.

Sadly there isn't an easy fix for this, and we're most likely going to have to completely wipe the series tracked prior to this change to avoid possible issues later on with Batoto series matching these prior IDs later down the line.

The good news from this is this will allow us to more easily migrate to MangaDex from Batoto in the future (although it still requires _someone_ to add the MangaDex equivalent series first).

Plan is to manually move/fix as much series as possible before this wipe (which is around 116~ series)

**Comment by DakuTree** [comment]
Fixed everything I could. Few don't have any chapters (but did before), and one series (Their Story) doesn't appear to exist at all anymore?

Will keep this open until it gets added again, as I don't want to remove it and we need to change the ID...

As for everything else, we really need some kind of solution for series with no chapter rather than manually marking them as ignored. Shall open a separate issue for that though.

**Comment by Vesnyx** [comment]
https://mangadex.org/manga/13939/tamen-de-gushi
Manga has been updated, issue can be closed?

**Comment by DakuTree** [comment]
Looks like it. Went and moved everyone following the old ID over as well.
