### ISSUE TITLE
Dashboard Topbar not Following on Scroll

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#284]
## Bug report

**What is the bug?**
The topbar on the trackr dashboard, along with the other tabs, the modify/delete, and the search bar does not follow user's scroll.

**Please provide steps to reproduce:**
Scroll on page lol.

**Where did the bug happen? (If applicable)**
On the dashboard.

**Comment by DakuTree** [comment]
Fixed as of 8ca5fb893d75465fa7db91307f8044362be5533a.
