### ISSUE TITLE
Userscript not working on mangadex if installed through violentmonkey

### ISSUE THREAD

**Issue by ramenchef** [DakuTree/manga-tracker#287]
Something with the mangadex update broke violentmonkey support on that site specifically. It still works on other support websites.

**Comment by rain2reign** [comment]
Can't say that i share your issue, as i also use violentmonkey... Can you be more detailed about it? Does it work that way (issue) in greasemonkey too or just violentmonkey? Cookie/cache/addons/extension conflict? 

PS: have you tried manually updating the script through the violentmonkey interface?

**Comment by ramenchef** [comment]
I have tried manually updating violentmonkey multiple times, disabled everything but violentmonkey, diabled any scripts but manga-tracker, cleared my cache, and cleared my cookies. I installed tampermonkey and the script and restored the api key and mangadex worked just fine with all extensions enabled.

Console is showing the following warnings/errors.

Sites initialized???
VM721:3 jQuery.Deferred exception: generateChapterList is not defined ReferenceError: generateChapterList is not defined
    at Object.setObjVars (<anonymous>:1164:23)
    at <anonymous>:2593:10
    at Object.preInit (<anonymous>:2618:33)
    at Object.init (<anonymous>:2592:8)
    at HTMLDocument.<anonymous> (<anonymous>:2564:28)
    at j (<anonymous>:3:29999)
    at k (<anonymous>:3:30313) undefined
r.Deferred.exceptionHook @ VM721:3
k @ VM721:3
setTimeout (async)
a.(anonymous function) @ VM720:3
(anonymous) @ VM721:3
i @ VM721:3
fireWith @ VM721:3
fire @ VM721:3
i @ VM721:3
fireWith @ VM721:3
ready @ VM721:3
S @ VM721:4
VM721:1164 Uncaught ReferenceError: generateChapterList is not defined
    at Object.setObjVars (<anonymous>:1164:23)
    at <anonymous>:2593:10
    at Object.preInit (<anonymous>:2618:33)
    at Object.init (<anonymous>:2592:8)
    at HTMLDocument.<anonymous> (<anonymous>:2564:28)
    at j (<anonymous>:3:29999)
    at k (<anonymous>:3:30313)

**Comment by DakuTree** [comment]
Should be fixed as of b9d61e8be9cc3d750eeb72c0faa2d45c8780469d.  
Re-open this if you're still having issues.
