### ISSUE TITLE
Mangadex Images

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#290]
This is just an FYI for anyone using Mangadex and still having issues. There are a few manga, ones that were uploaded very early on, that were stored on the original server, but have since been removed. This means that those images will not load at all until someone reuploads them.

One such example is here: https://mangadex.com/chapter/795/1
There is no actual image to load. This means that regardless of whatever we try to do, that image will not load since it doesn't exist on their server. 

If you are having an issue with MangaDex, try turning off our script and verifying if the image will display. Additionally, try to post any issues regarding the image loading aspect here to help consolidate the issues.

**Comment by honephiim** [comment]
hmmm... but there are still times where it's fine on MangaDex, but with the script, they don't load.
This one here for example: https://mangadex.com/chapter/9258/1

**Comment by Vesnyx** [comment]
Not having this issue. Seems like the '@require' script might be cached and not updated yet. 

You may also have to manually trigger an update for the script. Currently, I'm on 1.9.10 with no issues.

**Comment by honephiim** [comment]
You were right. I just had to update it. It's all good now. 

Thank you for the help.

**Comment by DakuTree** [comment]
Closed this by mistake earlier, whoops.

For now I've added a small note to the top of the viewer noting this issue until MangaDex can fix the remaining images. Will keep this issue open until then.

**Comment by Vesnyx** [comment]
Since it seems like MangaDex has stabilized and fixed the majority of their issues, I think we can close this issue. Perhaps we can remove the message or at least display it only if the manga has images that fail to load?

**Comment by Vesnyx** [comment]
Hey @DakuTree I'm pretty sure that the people over at MangaDex have finished their site functionality for the most part and are unlikely to swap image servers any time soon, so I think it may be fine to remove the notice as of now.
