### ISSUE TITLE
Script hides titles with link on MangaDex

### ISSUE THREAD

**Issue by honephiim** [DakuTree/manga-tracker#291]
## Bug report
_Delete this section if not applicable_

**What is the bug?**

No idea if I should call it a bug, but like the title says it, the script hides the title with link. Which may not seem like much. But that's the only way to go the manga page. Without that, I have to either disable the script or type the title in the search box. 

Here's a print. The title is on the top left. This one is called "Kuro".

![captura de ecra 24](https://user-images.githubusercontent.com/35668064/35361290-cf2ddeae-0158-11e8-936e-d1324092ad00.png)

**Comment by DakuTree** [comment]
Fixed as of 9e9ce4298ea9386f8c6b17dd4af309c63defa08e.
