### ISSUE TITLE
Add option/toggle to move topbar to bottom

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#295]
Often the topbar overlays on top of the sites own navbar which isn't great. This would work well as an easy temp solution until we can get that sorted.

**Comment by honephiim** [comment]
Thank you for considering it. I wasn't really confident on this one...

**Comment by doutatsu** [comment]
I was just about to suggest another improvement for the topbar. It'll be great to be able to hide it completely. I like to go full screen when reading manga and it just distracts me...

**Comment by honephiim** [comment]
Hmmm.... Being able to move the topbar to the bottom and being able to hide it seems like a good combo.
It wouldn't get in the way on most websites and neither while reading manga.

**Comment by honephiim** [comment]
What if when we went to Full Screen the top bar disappears? Then when we get out, it shows up again?
