### ISSUE TITLE
MangaDex - Updates being sent for series with no chapters or does not exist?

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#309]
Some examples:
* [21437 - Atsumare! Fushigi Kenkyu-bu](https://mangadex.com/manga/21437)
* [14822 - Futari no Renai Shoka](https://mangadex.com/manga/14822)
* [19436 - Ouji-Sama Nante Iranai](https://mangadex.com/manga/19436)
* [20796 - Interspecies Reviewers](https://mangadex.com/manga/20796)

404s:
* [23133](https://mangadex.com/manga/23133)
* [23213](https://mangadex.com/manga/23213)
* [23152](https://mangadex.com/manga/23152)
* [23100](https://mangadex.com/manga/23100)
* [23129](https://mangadex.com/manga/23129)
* [23165](https://mangadex.com/manga/23165)
* [23152](https://mangadex.com/manga/23133)

Spotted this in the error logs & not exactly sure what is causing it. Could also be caching of sorts.

There was some others ([DEAD Tube](https://mangadex.com/manga/13525) for example) which had chapters hidden since we weren't checking for R18 series, but that has been fixed. Not sure about the rest though.

**Comment by Vesnyx** [comment]
I can account for 21437. Apparently there was a chapter that existed on the site during the first two weeks of its existence. However, the chapter has since been deleted. Since nobody has bothered to upload any chapters, we're getting failed updates.

**Comment by Vesnyx** [comment]
I'm getting a bunch of title update fails on my end right now. I can only assume that there's some sort of issue going on with their hosting. Maybe there's a rate limit or a timeout going on?

**Comment by DakuTree** [comment]
@Vesnyx : Should be fixed now.  
Problem is they keep tweaking the site HTML every few days which breaks tends to break the xpath we use.

**Comment by Vesnyx** [comment]
Are these still errroring? I have no problems with tracking them right now. Only ones that generate issues are manga with no english chapters out. Everything else seems to be working fine.

**Comment by DakuTree** [comment]
The only ones causing errors that had chapters for a certain language, but no longer do (so the fix we did in 45c8adf6faaf9c5be9164304fd63c83da1c18e10 doesn't work here).
Will have a look into sorting that today.

**Comment by DakuTree** [comment]
Should all be fixed now.

Instead of just checking for the "No chapters" warning, we also check to see if any chapters exist that aren't in the language we're looking for. It should only fail if it doesn't match either of those checks (meaning the html has probably changed).
