### ISSUE TITLE
Add an option not to remove elements in order to avoid conflicts with Manga Loader

### ISSUE THREAD

**Issue by jackblk** [DakuTree/manga-tracker#311]
## Feature/Site Request
I've been using Manga Loader to read manga and using Manga Tracker along with it. If Manga Tracker loads before Manga Loader does, it will cause ML to fail to load manga pages since some elements are removed, and ML works on these elements.

If we can just have an option to turn off "removing elements", it will stop the conflict.

Manga Loader: https://github.com/fuzetsu/manga-loader

**Comment by Vesnyx** [comment]
#252 Duplicate-ish. It'll be done soon hopefully. :)

**Comment by jackblk** [comment]
Thanks for the reply! I think this is closed then :D.
