### ISSUE TITLE
Title from readmanga.today does not update

### ISSUE THREAD

**Issue by mikken** [DakuTree/manga-tracker#316]
## Bug report

_"Nana to Kaoru"_ from _readmanga.today_ does not update showing this message on _trackr.moe_:

___
Some of the series on your list have been marked as inactive and have not been updated due to either: no active users or having trouble updating.
These will be updated during the next update (Within next 4hrs~).
If this continues to appear, please submit a bug report. 
___

More than 4 hours have passed since I added it.

I also had trouble adding other titles from _readmanga.today_ ("Internal server error" on update).

**Comment by DakuTree** [comment]
Just pushed out a fix ( https://github.com/DakuTree/manga-tracker/commit/68939a28b4c2faec0b20a47ec93d72320420d255#diff-3d27738ae6e6cb948d4beb0d6fff9cbdR315 ) which should have fixed this.
