### ISSUE TITLE
1, X1 pages don't load on MangaHere

### ISSUE THREAD

**Issue by jacobmix** [DakuTree/manga-tracker#322]
## Bug report

**Pages 1, 11, 21, 31, ect don't load on http://www.mangahere.cc/ with the  single page loader**

For now i'll just disable the single page loader. But it's a weird issue. Might be related to #214 
Tho it doesn't happen on http://fanfox.net/ (MangaFox)

**Comment by DakuTree** [comment]
Small update, seeing this occur on one device I use, and on MangaFox (not MangaHere). Still not happening on main PC though, which is a bit odd.

**Comment by jacobmix** [comment]
Don't have the problem on MangeHere anymore after updating script, and trying again today.
Tested with the same series, and some others. Seems fine on MangaFox as well.

**Comment by jacobmix** [comment]
Nope, wait. First page now loads. But 11, 21, 31, ect. Still don't.
Still works fine on MangaFox tho.

**Comment by jacobmix** [comment]
Page not loading: 
![Page not loading](https://prnt.sc/ihkfxj)
If i click the image: 
![Failed to load image again](http://prntscr.com/ihkg67)
It's weird since the image loads fine when i'm not using the single page loader.
