### ISSUE TITLE
Series Conflict?

### ISSUE THREAD

**Issue by lostguru** [DakuTree/manga-tracker#327]
## Bug report

At least I think it's a bug...

**What is the bug?**

"Kuzumi-kun, Kuuki Yometemasu ka?" (MangaDex) began showing up as "Sadamitsu the Destroyer" on my tracker recently.

![image](https://user-images.githubusercontent.com/3195451/36520212-c307e870-175d-11e8-9df8-dc64b715e053.png)

The series and latest release links go to the latter respective pages (https://mangadex.com/manga/23059 and https://mangadex.com/chapter/83949), but the My Status link still links to the latest chapter i read (https://mangadex.com/chapter/84833)

**Please provide steps to reproduce:**

Maybe it can be reproduced by visiting https://mangadex.com/chapter/84833 and clicking the book to follow.

**Comment by DakuTree** [comment]
Think this may have been an error on my part. MangaDex keeps changing IDs of newly added series to match their old Batoto IDs, and every time this happens it requires a manual fix.  
"Sadamitsu the Destroyer" was one of the series requiring a fix, but must have moved the wrong series by mistake. Have moved everything back now.

**Comment by lostguru** [comment]
Got it, thanks!
