### ISSUE TITLE
Script no longer functions with ViolentMonkey - API key cannot be generated

### ISSUE THREAD

**Issue by bVork** [DakuTree/manga-tracker#332]
## Bug report

**What is the bug?**
I think a recent update to the script has rendered it incompatible with ViolentMonkey. No longer can I generate an API key, meaning the script won't work on a new device. However, existing installs of the userscript that have had the API key previously generated continue to function, though the key is displayed as "not set".

Uninstalling ViolentMonkey and installing the userscript with TamperMonkey allows it to work again, but I don't consider this solution ideal because of TamperMonkey's questionable EULA and code obfuscation.

**Please provide steps to reproduce:**
1. Install ViolentMonkey (any version - I tried rolling back multiple versions to a month ago, when it was working. No dice)
2. Install userscript
3. Log in. (Clearing cookies and cache does not seem to affect this - I tried.)
4. Click in vain at the "generate API key"

**Other relevant information:**
OS: Windows 10. (Also tried with Windows 7 - same result)
Browser: Mozilla Firefox 58.0.2
ViolentMonkey version: 2.8.29, 2.8.27, 2.8.26
TamperMonkey version: 4.6.5709
Userscript version: 1.10.12

**Comment by DakuTree** [comment]
Not seeing this on my end. It's possible there is another extension causing issues for some reason (Privacy Badger for example).

If you could check the console (Ctrl+Shift+K) and see if anything pops up after clicking either API link that would be useful.

**Comment by bVork** [comment]
The bug seems to have been fixed. I notice that there was a script update in the last few hours, and now the same procedure that would refuse to give me an API key in ViolentMonkey now works just fine. Thank you.
