### ISSUE TITLE
MangaDex - Switch to using RSS

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#335]
Apparently RSS works now, so it would be a good idea to switch over when possible. Even though the site changes have somewhat stabilized, I would rather use something that won't change at all, to avoid tracking breaking again.

**Comment by DakuTree** [comment]
Had a look at the RSS feeds and I'm not sure if this is a good idea. Problem is we can't get different RSS feeds depending on language which causes issues, and there isn't a safe was to always get the series title either.

**Comment by xrogaan** [comment]
You can actually filter the language, but it require filtering them before requesting the rss feed. It is defined by the `mangadex_filter_langs` cookie, containing an integer.

You can test it yourself by clicking the globe icon at the top.

**Comment by DakuTree** [comment]
No longer needed as the new beta provides a proper API which we'll be using instead. See #361 for more info.
