### ISSUE TITLE
MangaStream Chapter Selection

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#336]
## Bug report

**What is the bug?**
Chapter displayed by selection is always the first one in the list, not the one selected.

**Please provide steps to reproduce:**
Visit a page:
https://readms.net/r/dr_stone/052/4992
Notice how the chapter selection shows chapter 1 instead of the current chapter.

Probably due to some mismatch in the URLs.

**Comment by DakuTree** [comment]
Not seeing this on my end.
Initial guess is the title page not showing new chapters right away, which would cause this issue.

Next time this happens if you could have a check on the chapter list to see if the chapter you're viewing is actually on the chapter list at all, that would help.

**Comment by Vesnyx** [comment]
https://readms.net/r/neverland/081/4998

When I'm on this URL, this is the chapter select list. I think that the URL's from the main chapter list have the page number and some additional parameters included. However, the URL for the chapter linked from trackr doesn't include it. 
![image](https://user-images.githubusercontent.com/4986454/38239274-1d664882-36e1-11e8-9f4f-f2d493089968.png)

**Comment by Vesnyx** [comment]
Okay I figured out the issue. 

this.chapterListCurrent = '/r/'+this.title+'/'+this.chapter+'/1';

This line in MangaStream's URL doesn't include the extra params. 

Here's a fix:
this.chapterListCurrent = '/r/'+this.title+'/'+this.chapter+'/1?f=0&e=1';
But this is kinda messy and also doesn't match with the URL that trackr provides as a link. 🤷‍♂️

**Comment by DakuTree** [comment]
No idea what is adding those extra params, because they aren't appearing on my end.
![](https://i.imgur.com/UJfU3xB.png)

I've pushed a fix which should strip those params from the chapter list so it matches correctly.
