### ISSUE TITLE
Can I get the SQL dump of this PHP server?

### ISSUE THREAD

**Issue by softdev999** [DakuTree/manga-tracker#339]
## Bug report
_Delete this section if not applicable_

**What is the bug?**

**Please provide steps to reproduce:**

**Where did the bug happen? (If applicable)**

---

## Feature/Site Request
_Delete this section if not applicable_

**What is the feature?**

**Other relevant information:**

**Comment by DakuTree** [comment]
Nope.

**Comment by DakuTree** [comment]
Nope.

**Comment by DakuTree** [comment]
Nope.

**Comment by DakuTree** [comment]
Nope.

**Comment by softdev999** [comment]
Yeah, You shared the backend code, why do you mind to share database SQL dump for others then?
Can we have a better discussion on live chat?
