### ISSUE TITLE
Says i'm out of date even after updating (reinstalling script)

### ISSUE THREAD

**Issue by jacobmix** [DakuTree/manga-tracker#340]
## Bug report

The option page says i'm out of date. But i've tried updating/reinstalling the script multiple times.
Here's a [screenshot](https://i.imgur.com/pVlu4Pl.png) that shows my version, ect.
Some stuff has been censored tho. Like my API key, and the code below the version #, and update date.
Note: Latest commit was on Apr 10, 2018.

**Comment by DakuTree** [comment]
Forgot to update the version listed on the backend.  
Should be fixed as per 4eeabd9c6b949c58c6afc2f4b562ea2f786d35aa.
