### ISSUE TITLE
Mangarock Tracker Not Loading

### ISSUE THREAD

**Issue by dragonfoxsl** [DakuTree/manga-tracker#342]
## Bug report

**What is the bug?**
Can not load manga-tracker on https://mangarock.com

**Please provide steps to reproduce:**
I have setup manga-tracker and just like normal when I go to any mangarock chapter
the tracker is not loading I tried refreshing and a fresh install of chrome but still not working.
Other sites I use http://mangakakalot.com/ and http://www.mangahere.cc/ is working 
the only issue is on mangarock.

**Comment by doutatsu** [comment]
Can confirm, it happens for me as well

**Comment by DakuTree** [comment]
Should be fixed as per above commit. Re-open the issue still occurs after updating the userscript (v1.10.25).
