### ISSUE TITLE
Hatigarmscans new website

### ISSUE THREAD

**Issue by SonnyX** [DakuTree/manga-tracker#354]
## Bug report
**What is the bug?**
Hatigarmscans changed websites( and stopped using foolslides?):
https://www.hatigarmscans.net/

**Comment by Vesnyx** [comment]
Yep, it's now on the same one that's used by FallenAngels.

**Comment by DakuTree** [comment]
Looks like they've switched to using myMangaReaderCMS.  
They're also missing a lot of of their old series. We have 34 tracked, but the new site only has 15.

Will look into sorting this tomorrow morning.

**Comment by Vesnyx** [comment]
Getting some Unable to update errors. Can't tell if caused by userscript sending bad info or the backend not working properly since my Chrome isn't showing the userscript network requests for some reason.

**Comment by SonnyX** [comment]
```// @include      /^https?:\/\/(?:www\.)?hatigarmscans\.net\/[a-z]+\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9\._-]+[\/]*[0-9]*$/```
Fixes the user-script, however gets an unable to update.
See: [Tales of demons and gods chapter 177-5](https://hatigarmscans.net/manga/tales-of-demons-and-gods/chapter-177-5/1)

**Comment by Vesnyx** [comment]
Needs to be fixed on php side as well. Also, not sure if this fixes the issue that Shomin Sample was having with updates as well.

**Comment by DakuTree** [comment]
Fixed as of 3c6bf81041e49ae9ad6808548a2e3a76ab10ef42.
