### ISSUE TITLE
Blocked by OVH hosting? (Broke OneTimeScans, SeaOtterScans & RavensScans)

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#356]
All sites that seem to use OVH hosting are now throwing:
```curl: (7) Failed to connect to ... port 80/443: Connection refused```
Non-curl methods also return the same issue.

Other sites still appear to work fine, and it appears to work fine when trying to access the OVH sites from another machine.

Initial guess was some weird DNS issue, but it doesn't seem to be the case.

I'm assuming this has to be a manual IP block? It's a bit weird it's at a global host level though.  
It's possible that the owner of the three sites is the same, and that's why we're seeing this. Still a bit odd.

**Comment by SonnyX** [comment]
All three websites appear to be down, or redirecting to "plesk"

**Comment by DakuTree** [comment]
Now it looks like the sites are working again. I have to assume this is just some weird issue with their host.

Re-enabled for now. Will re-open this issue if anything pops up again.
