### ISSUE TITLE
Site error: An Error Was Encountered (valid configuration array)

### ISSUE THREAD

**Issue by jacobmix** [DakuTree/manga-tracker#358]
## Bug report

When i go to the site ( https://trackr.moe/ ) i just get:
"**An Error Was Encountered**
Your /var/www/trackr.moe/releases/1.1/application/config/_secure/sites.php file does not appear to contain a valid configuration array."
Picture: http://prntscr.com/k04e0r

**Comment by DakuTree** [comment]
Fixed now. Trying to move to using a new deployment method and having issues 😅 .

**Comment by jacobmix** [comment]
Can get to the site now, but the site icon isn't showing up: http://prntscr.com/k04mpp

**Comment by jacobmix** [comment]
Also now it says there's a new version of the script every time i click:
"Mark this chapter as latest chapter read"

**Comment by DakuTree** [comment]
Both problems should be fixed now.
