### ISSUE TITLE
Installing latest userscript fails in greasemonkey

### ISSUE THREAD

**Issue by Isotab** [DakuTree/manga-tracker#362]
## Bug report

**What is the bug?**
When trying to update to the latest version of the userscript I am getting a 404 error for the less file

**Please provide steps to reproduce:**
Try to update or fresh install via both github raw and the website url.

Setup
- Firefox 61.0.1 64 bit
- Greasemonkey 4.5

I got it to work by going back in history on here and ended up using version 1.11.1
---

User script download failed
404 - Not Found at https://trackr.moe/userscripts/assets/main.9.less

**Comment by DakuTree** [comment]
Should be fixed now.
