### ISSUE TITLE
Latest update (1.11.6 > 1.11.7) breaks script while using violentmonkey

### ISSUE THREAD

**Issue by ramenchef** [DakuTree/manga-tracker#363]
I am getting the following error in the console:
VM1010:3 Error running script: Manga Tracker
TypeError: Cannot read property 'includes' of undefined
Cannot read property 'includes' of undefined

The website does not recognize the script being installed. I have tried disabling my other extensions that may interfere (ublock, privacy badger) and uninstalling and reinstalling the script. I have also tried clearing all website data including cookies. This is on Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by DakuTree** [comment]
Fixed as per the above commit (v1.11.8).

**Comment by DakuTree** [comment]
Missed something in the previous fix, 1.11.9 should resolve any remaining issues.
