### ISSUE TITLE
MangaFox/MangaHere support temporarily disabled

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#369]
Due to constant downtime, I've decided to disable support for both of these sites.  
They've been getting less and less stable over the past few months, to the point where many series are actually getting marked as inactive due to constant failed updates.

Unless things improve, both sites will stay disabled for now. Would highly recommend migrating to another site where possible.

**Comment by Stubbs9410** [comment]
how long? my entire list is red :(

**Comment by DakuTree** [comment]
I've re-enabled them since they both appear to be back up.

**Comment by Stubbs9410** [comment]
thx you rock :)
