### ISSUE TITLE
Mangadex support obsolete

### ISSUE THREAD

**Issue by bicobus** [DakuTree/manga-tracker#376]
## Bug report

Mangadex reader recently got updated, and subsequently gets broken by the user script provided by trackr.moe

If you go on mangadex with the script active and try to read a chapter of a random serie, the first image will show up just fine, but subsequent clicks will generate an error:

```Render error TypeError: e is null
Stack trace:
value@https://mangadex.org/scripts/reader.min.js?1534030752:1:75814
value/<@https://mangadex.org/scripts/reader.min.js?1534030752:1:80268
a@https://mangadex.org/scripts/reader.min.js?1534030752:1:119093
R/<@https://mangadex.org/scripts/reader.min.js?1534030752:1:119238
s@https://mangadex.org/scripts/reader.min.js?1534030752:1:24965
 reader.min.js:1:80525
```

Disabling the trackr.moe user script solve the reader issue.

**Comment by DakuTree** [comment]
I'm not seeing this issue.

Are you running the latest version of the userscript (1.12.15)?
Are you using the default or legacy mangadex reader? (Which is set via https://mangadex.org/settings)
What browser are you on?

**Comment by bicobus** [comment]
I wasn't aware that there was a legacy reader. Thanks for pointing that out.
