### ISSUE TITLE
"Done Reading" tab

### ISSUE THREAD

**Issue by goudekid** [DakuTree/manga-tracker#384]
It'd be nice to have a tab to store series that I've finished reading so they don't clutter my main list. I could put them in On-hold but those definitely have two different meaning and I'd like to have them organized properly.

Something I wouldn't recommend: trying to automatically place manga in this group when a series is marked as completed somewhere and the user reads what is apparently the last chapter; reason being that many sites mark series as complete erroneously but they still get updated. (Dorohedoro for example on a few sites)

**Comment by DakuTree** [comment]
There is a bit on the options page to add up to 3 new lists which should solve your problem.

**Comment by goudekid** [comment]
I managed to completely miss it despite searching for it for a few minutes. My appologies.
