### ISSUE TITLE
Request: Proxy links to kissmanga

### ISSUE THREAD

**Issue by goudekid** [DakuTree/manga-tracker#385]
For example, Goblin Slayer is not present in english on MangaDex, my first choice of reader, but is on KissManga, which seems to have blanket banned tracking by trackr.moe. Could we just track releases using a different site but still get links to KissManga somehow?

**Comment by DakuTree** [comment]
Not going to happen since assuming what the chapter links would be cause into loads of issues later on.  
Also not really up for supporting a site which has blocked us either.
