### ISSUE TITLE
Mangakakalot tracker not working with https

### ISSUE THREAD

**Issue by MitsuhideA** [DakuTree/manga-tracker#392]
## Bug report

**What is the bug?**
Cannot load the tracker on https://mangakakalot.com/
**Please provide steps to reproduce:**
Go on any manga chapter. The userscript does not load.

Modifying the line 58 in the userscript from this: 
`// @include      /^http:\/\/mangakakalot\.com\/chapter\/[a-zA-Z_\-0-9]+\/chapter_[0-9\.]+$/`
to this: 
`// @include      /^https?:\/\/mangakakalot\.com\/chapter\/[a-zA-Z_\-0-9]+\/chapter_[0-9\.]+$/` 
makes it work.

**Comment by LoganGirard** [comment]
I currently have a pull request out for this fix.

https://github.com/DakuTree/manga-tracker/pull/393

**Comment by DakuTree** [comment]
Fixed as of #393.
