### ISSUE TITLE
Unable to run php unit tests locally

### ISSUE THREAD

**Issue by LoganGirard** [DakuTree/manga-tracker#395]
When I try to run 'phpunit .' in the tests folder, I get the following:

Your system folder path does not appear to be set correctly. Please open the following file and correct this: Bootstrap.php

Issue seems to be that the system path: '../../vendor/codeigniter/framework/system'

is not committed so my path resolution fails. Should that part be committed?

**Comment by DakuTree** [comment]
`/vendor/` is composer dependencies, so a `composer install` is needed.

You can also have a look at the [travis.yml](https://github.com/DakuTree/manga-tracker/blob/master/.travis.yml#L40) file for further example on how we run tests.
