### ISSUE TITLE
Meraki Scans double URL

### ISSUE THREAD

**Issue by r0bodog** [DakuTree/manga-tracker#406]
## Bug report
_Delete this section if not applicable_

**What is the bug?**
https://merakiscans.com/ 
all mangas

**Please provide steps to reproduce:**
1 )Open Meraki Scans manga by link: https://merakiscans.com/a-returner-s-magic-should-be-special/38/
2) Console shows 404 error and tracker isn't shown
3) Error for https://merakiscans.com/manga/a-returner-s-magic-should-be-special/https://merakiscans.com/a-returner-s-magic-should-be-special/38//00.png

**Where did the bug happen? (If applicable)**

https://merakiscans.com/a-returner-s-magic-should-be-special/38/

---

**Other relevant information:**

Cause seems to be the tracker trying to open the pages but doubling the URL and adding an extra / before the image:
**https://merakiscans.com/manga/a-returner-s-magic-should-be-special/**https://merakiscans.com/a-returner-s-magic-should-be-special/38/**/00.png**

**Comment by miguelenam** [comment]
https://i.imgur.com/0KnLLfP.png

**Comment by r0bodog** [comment]
It's fixed now. Thanks!
