### ISSUE TITLE
Wrong language chapters being tracked on MangaDex

### ISSUE THREAD

**Issue by kaszak** [DakuTree/manga-tracker#408]
## Bug report

**What is the bug?**

Today i noticed some of my tracked manga suddenly got a lot of new chapters, but unfortunately it turns out they are not legible for me, Tracker seems to have forgotten about language differences. For example, [ Osananajimi ni Najimitai](https://mangadex.org/manga/23051) ch 12 is listed on the Tracker as newest, but it's in Russian, not the English it initially tracked. Same with [Hige Wo Soru](https://mangadex.org/manga/32043) (the Spanish 2nd chapter is listed as newest) and [One Punch Man](https://mangadex.org/manga/7139), where ch v17/c137 in Russian is shown as newest.

**Please provide steps to reproduce:**

Be subscribed to English [ Osananajimi ni Najimitai](https://mangadex.org/manga/23051). Newest chapter should be the English ch 9, not Russian ch 12.

**Comment by DakuTree** [comment]
Fix has been pushed.

Having to do a manual fix to fix any series affected, since we might have some series that are now a higher chapter due to the language switch.
