### ISSUE TITLE
Re-enable Fallen Angel Scans

### ISSUE THREAD

**Issue by HelloEh** [DakuTree/manga-tracker#419]
## Feature/Site Request

**What is the feature?**
Re-enable FallenAngelScans (manga.fascans.com) for tracking.
**Other relevant information:**
Recently, manga.fascans.com was under DDoS attack for over a week. A CloudFlare "wait" page was present during this time, which is likely what caused manga-tracker to auto-disable the site. That DDoS was concluded a few weeks ago, but the site is still not being tracked.

**Comment by DakuTree** [comment]
Done.
