### ISSUE TITLE
Mangastream Issue

### ISSUE THREAD

**Issue by groundhogxp** [DakuTree/manga-tracker#83]
Hi,

It seems that the tracker is no longer compatible with Mangastream for some reason.

**Comment by DakuTree** [comment]
This is fixed as per the above commit.
Might need to manually update the userscript to get the fix right away. Should be on version 1.4.3.

**Comment by cublikefoot** [comment]
I'm getting an error when trying to add a series from Mangastream after this change. Just says "ERROR: Unable to update"

http://puu.sh/v4cUa/5206c2ba9d.png

**Comment by DakuTree** [comment]
@cublikefoot Should be working now. Forgot to tweak the site whitelist with the new domain. :sweat:
